// GENERATED by scripts/build-hoop-family-svgs.mjs from
// scripts/hoop-family-stations.json. Do not edit; change the table and re-run.
//
// Boxes and tip points are in glyph units on a grip-centred box with the prop
// across +x. Reaches and stations are in metres for the 3D renderers.

export interface HoopFamilyBox {
  readonly width: number;
  readonly height: number;
}

export interface HoopFamilyTip {
  readonly dx: number;
  readonly dy: number;
}

export interface HoopFamilyCrop {
  readonly imageWidth: number;
  readonly imageHeight: number;
  readonly x: number;
  readonly y: number;
  readonly width: number;
  readonly height: number;
}

export const HOOP_FAMILY_BOXES = {
  minihoop: { width: 257.9, height: 138.2 },
  bighoop: { width: 600, height: 300 },
  triangle: { width: 280.3, height: 162.17 },
} as const satisfies Record<string, HoopFamilyBox>;

export const HOOP_FAMILY_TIP_POINTS = {
  minihoop: [
    { dx: 10.37, dy: -35.62 },
    { dx: 78.13, dy: -57.63 },
    { dx: 120, dy: 0 },
    { dx: 78.13, dy: 57.63 },
    { dx: 10.37, dy: 35.62 },
  ],
  bighoop: [
    { dx: 34.6, dy: -83.7 },
    { dx: 193.8, dy: -135.43 },
    { dx: 292.2, dy: 0 },
    { dx: 193.8, dy: 135.43 },
    { dx: 34.6, dy: 83.7 },
  ],
  triangle: [
    { dx: 135.15, dy: 0 },
    { dx: 129.18, dy: 74.58 },
    { dx: 129.18, dy: -74.58 },
    { dx: 61.61, dy: 42.46 },
    { dx: 61.61, dy: -42.46 },
  ],
  triangle_side: [
    { dx: 135.15, dy: 0 },
    { dx: 5.97, dy: 74.58 },
    { dx: 5.97, dy: -74.58 },
    { dx: 73.54, dy: 42.46 },
    { dx: 73.54, dy: -42.46 },
  ],
} as const satisfies Record<string, readonly HoopFamilyTip[]>;

export const HOOP_FAMILY_GLYPH_CROPS = {
  minihoop: {
    imageWidth: 257.9,
    imageHeight: 138.2,
    x: 121.25,
    y: 2,
    width: 134.2,
    height: 134.2,
  },
  bighoop: {
    imageWidth: 600,
    imageHeight: 300,
    x: 297.65,
    y: 0,
    width: 302.35,
    height: 300,
  },
  triangle: {
    imageWidth: 280.3,
    imageHeight: 162.17,
    x: 133.65,
    y: 0,
    width: 146.65,
    height: 162.17,
  },
} as const satisfies Record<string, HoopFamilyCrop>;

/** Hand to the far tube centreline, in metres. Hoops: across the ring. Triangle: height plus one sagitta, both grips. */
export const HOOP_FAMILY_REACH_M = {
  minihoop: 0.45402499999999996,
  bighoop: 0.635635,
  triangle: 0.5062849956347443,
} as const;

/** Triangle stations in metres; Triangle3D.svelte and the worker mirror restate these and tests pin them here. */
export const TRIANGLE_STATIONS_M = {
  sideChord: 0.5588,
  sagitta: 0.022350000000000002,
  bowRadius: 1.7575812639821025,
  arcAngle: 0.319291492132703,
  height: 0.4839349956347443,
  reach: 0.5062849956347443,
  tubeRadius: 0.0079375,
  sleeveRadius: 0.01031875,
  elbowLeg: 0.05,
} as const;

/** Hoop hardware in metres: the join tape, its button, and the grip wrap. */
export const HOOP_HARDWARE_M = {
  joinTape: 0.045,
  button: 0.006,
  gripTape: 0.15,
  hardwareRatio: 1.3,
} as const;
