import { PropType } from "./enums/prop-type";

/**
 * Where the hand holds the triangle. Both are real: a corner grip wraps the
 * printed elbow, a side grip wraps the bow point of one side. The frame is the
 * same object either way and reaches the same distance (spec section 2), so
 * the grip is an appearance choice like a fan build, never notation.
 */
export const TRIANGLE_GRIPS = ["corner", "side"] as const;
export type TriangleGrip = (typeof TRIANGLE_GRIPS)[number];

export const DEFAULT_TRIANGLE_GRIP: TriangleGrip = "corner";

export function normalizeTriangleGrip(value: unknown): TriangleGrip {
  return value === "side" ? "side" : DEFAULT_TRIANGLE_GRIP;
}

export function isTrianglePropType(
  propType: string | null | undefined
): boolean {
  return propType?.toLowerCase() === PropType.TRIANGLE;
}

/**
 * Renderer-only identity, like `resolveFanRenderKey`: the corner grip is the
 * notation glyph, the side grip is a look on top of it. Never enters PropType,
 * choreography, or URLs.
 */
export function resolveTriangleRenderKey(
  propType: string,
  grip: TriangleGrip
): string {
  const normalized = propType.toLowerCase();
  if (!isTrianglePropType(normalized) || grip === "corner") return normalized;
  return `${normalized}__side`;
}

/**
 * The captured model sprite for a grip. The save endpoint only accepts
 * `[a-z0-9_]`, so the side sprite is `triangle_side`, not `triangle-side`.
 */
export function triangleSpriteKey(grip: TriangleGrip): string {
  return grip === "side" ? "triangle_side" : PropType.TRIANGLE;
}

/**
 * Parsed from either the glyph key `triangle__side` or the sprite key
 * `triangle_side`: both name the triangle's side grip.
 */
export interface TriangleRenderKey {
  propType: "triangle";
  grip: "side";
}

export function parseTriangleRenderKey(
  value: string
): TriangleRenderKey | null {
  const normalized = value.toLowerCase();
  if (normalized === "triangle__side" || normalized === "triangle_side") {
    return { propType: "triangle", grip: "side" };
  }
  return null;
}

export function triangleAppearanceArtwork(grip: TriangleGrip): string | null {
  if (grip === "corner") return null;
  // Generated by scripts/build-hoop-family-svgs.mjs on the same box as
  // pictograph/triangle.svg, so placements and trails stay in frame.
  return "/images/props/appearances/triangle-side.svg?v=1";
}

export interface TriangleGripOption {
  id: TriangleGrip;
  label: string;
}

export const TRIANGLE_GRIP_OPTIONS: readonly TriangleGripOption[] = [
  { id: "corner", label: "Corner" },
  { id: "side", label: "Side" },
];
