/**
 * Shared harness for the animation-clock audit.
 *
 * Everything under test is PRODUCTION code — `AnimationPlaybackController`,
 * `AnimationLoop`, `SequenceAnimationOrchestrator`, `AnimationStateManager` and
 * the pure helpers in `step-calculator`. The only doubles here are:
 *
 *  - `createPanelStateDouble()` — a plain object standing in for the Svelte
 *    rune-backed `AnimationPanelState`. It is a value container with no timing
 *    logic of its own; every number it holds is written by the controller.
 *  - `createFrameClock()` — a deterministic `requestAnimationFrame` /
 *    `performance.now` pair so a frame budget can be dictated exactly and a
 *    hidden tab (time advances, no frames delivered) can be simulated.
 *
 * Sequences come from `tests/fixtures/loop-audit/real-loop-fixtures.json`,
 * generated by `scripts/generate-loop-audit-fixtures.mjs` off the production
 * generation pipeline, so they are canonical valid sequences rather than
 * hand-built partials.
 */

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { normalizeLegacySteps } from "@tka/tka-types";
import type { SequenceData } from "$lib/shared/foundation/domain/models/sequence-data";
import type { StepData } from "$lib/shared/foundation/domain/models/step-data";
import type { PropState } from "$lib/shared/foundation/domain/types/prop-state";
import type {
  AnimationPanelState,
  PlaybackMode,
  StepPlaybackStepSize,
} from "$lib/shared/animation-engine/state/animation-panel-state.svelte";
import {
  PLAYBACK_MAX_SPEED,
  PLAYBACK_MIN_SPEED,
} from "$lib/shared/animation-engine/domain/constants/timing";

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../../.."
);

interface FixtureSample {
  loopType: string;
  seedWord: string;
  derivedWord: string;
  letterStepCount: number;
  steps: unknown[];
}

let fixtureCache: Record<string, FixtureSample[]> | null = null;

function loadFixtures(): Record<string, FixtureSample[]> {
  fixtureCache ??= JSON.parse(
    readFileSync(
      path.join(repoRoot, "tests/fixtures/loop-audit/real-loop-fixtures.json"),
      "utf8"
    )
  ) as Record<string, FixtureSample[]>;
  return fixtureCache;
}

function toSequence(sample: FixtureSample, id: string): SequenceData {
  const steps = normalizeLegacySteps(sample.steps) as unknown as StepData[];
  const startPosition = steps.find((step) => step.stepNumber === 0) ?? null;
  return {
    id,
    name: sample.seedWord,
    word: sample.derivedWord,
    author: "loop-audit",
    steps,
    startPosition,
    isCircular: true,
    thumbnails: [],
  } as unknown as SequenceData;
}

/**
 * A canonical CIRCULAR sequence (end pose === start pose, orientations match),
 * so `isSeamlesslyLoopable` is true and the controller takes the seamless
 * branch: no repeated start hold, no end hold.
 */
export function canonicalSeamlessSequence(
  loopType = "rotated",
  index = 0
): SequenceData {
  const sample = loadFixtures()[loopType]?.[index];
  if (!sample) throw new Error(`No fixture for ${loopType}[${index}]`);
  return toSequence(sample, `seamless-${loopType}-${index}`);
}

/**
 * A canonical sequence truncated before its closing beat, so it does NOT come
 * back to its opening pose. The controller takes the freeform branch: a start
 * hold replayed on every pass plus a one-beat end hold.
 */
export function canonicalFreeformSequence(
  loopType = "rotated",
  index = 0,
  dropTrailingSteps = 1
): SequenceData {
  const base = canonicalSeamlessSequence(loopType, index);
  const steps = base.steps as unknown as StepData[];
  return {
    ...base,
    id: `${base.id}-freeform`,
    isCircular: false,
    steps: steps.slice(0, steps.length - dropTrailingSteps),
  } as unknown as SequenceData;
}

/** Replace the per-motion-step durations (start position keeps no duration). */
export function withStepDurations(
  sequence: SequenceData,
  durations: readonly number[]
): SequenceData {
  let motionIndex = 0;
  const steps = (sequence.steps as unknown as StepData[]).map((step) => {
    if (step.stepNumber === 0) return step;
    const duration = durations[motionIndex % durations.length]!;
    motionIndex += 1;
    return { ...step, duration };
  });
  return { ...sequence, steps } as unknown as SequenceData;
}

/** Independent sum of the motion-step durations (the harness's own arithmetic). */
export function motionDurationTotal(sequence: SequenceData): number {
  return (sequence.steps as unknown as StepData[])
    .filter((step) => step.stepNumber !== 0)
    .reduce((sum, step) => sum + (step.duration ?? 1), 0);
}

/** Independent per-motion-step duration list. */
export function motionDurations(sequence: SequenceData): number[] {
  return (sequence.steps as unknown as StepData[])
    .filter((step) => step.stepNumber !== 0)
    .map((step) => step.duration ?? 1);
}

// ── Panel-state double ───────────────────────────────────────────────────────

export interface PanelStateDouble extends AnimationPanelState {
  readonly stepHistory: readonly number[];
  setShouldLoop: (loop: boolean) => void;
  setPlaybackMode: (mode: PlaybackMode) => void;
  setStepPlaybackPauseMs: (ms: number) => void;
  setStepPlaybackStepSize: (size: StepPlaybackStepSize) => void;
}

export function createPanelStateDouble(
  overrides: {
    shouldLoop?: boolean;
    speed?: number;
    playbackMode?: PlaybackMode;
    stepPlaybackPauseMs?: number;
    stepPlaybackStepSize?: StepPlaybackStepSize;
  } = {}
): PanelStateDouble {
  let currentStep = 0;
  let isPlaying = false;
  let speed = overrides.speed ?? 1;
  let shouldLoop = overrides.shouldLoop ?? true;
  let playbackMode: PlaybackMode = overrides.playbackMode ?? "continuous";
  let stepPlaybackPauseMs = overrides.stepPlaybackPauseMs ?? 300;
  let stepPlaybackStepSize: StepPlaybackStepSize =
    overrides.stepPlaybackStepSize ?? 1;
  let totalSteps = 0;
  let sequenceWord = "";
  let sequenceAuthor = "";
  let leftPropState: PropState = { centerPathAngle: 0, staffRotationAngle: 0 };
  let rightPropState: PropState = { centerPathAngle: 0, staffRotationAngle: 0 };
  let sequenceData: SequenceData | null = null;
  const stepHistory: number[] = [];

  return {
    get currentStep() {
      return currentStep;
    },
    get isPlaying() {
      return isPlaying;
    },
    get speed() {
      return speed;
    },
    get shouldLoop() {
      return shouldLoop;
    },
    get playbackMode() {
      return playbackMode;
    },
    get stepPlaybackPauseMs() {
      return stepPlaybackPauseMs;
    },
    get stepPlaybackStepSize() {
      return stepPlaybackStepSize;
    },
    get totalSteps() {
      return totalSteps;
    },
    get sequenceWord() {
      return sequenceWord;
    },
    get sequenceAuthor() {
      return sequenceAuthor;
    },
    get leftPropState() {
      return leftPropState;
    },
    get rightPropState() {
      return rightPropState;
    },
    get sequenceData() {
      return sequenceData;
    },
    get stepHistory() {
      return stepHistory;
    },
    setCurrentStep: (step: number) => {
      currentStep = step;
      stepHistory.push(step);
    },
    setIsPlaying: (playing: boolean) => {
      isPlaying = playing;
    },
    setSpeed: (next: number) => {
      // Mirrors the real AnimationPanelState clamp so the double cannot make
      // the controller look better-behaved than production.
      speed = Math.max(PLAYBACK_MIN_SPEED, Math.min(PLAYBACK_MAX_SPEED, next));
    },
    setShouldLoop: (loop: boolean) => {
      shouldLoop = loop;
    },
    setPlaybackMode: (mode: PlaybackMode) => {
      playbackMode = mode;
    },
    setStepPlaybackPauseMs: (ms: number) => {
      stepPlaybackPauseMs = ms;
    },
    setStepPlaybackStepSize: (size: StepPlaybackStepSize) => {
      stepPlaybackStepSize = size;
    },
    setTotalSteps: (steps: number) => {
      totalSteps = steps;
    },
    setSequenceMetadata: (word: string, author: string) => {
      sequenceWord = word;
      sequenceAuthor = author;
    },
    setPropStates: (left: PropState, right: PropState) => {
      leftPropState = left;
      rightPropState = right;
    },
    setSequenceData: (data: SequenceData | null) => {
      sequenceData = data;
    },
  } as unknown as PanelStateDouble;
}

// ── Deterministic frame clock ────────────────────────────────────────────────

export interface FrameClock {
  /** Current fake `performance.now()` value, in ms. */
  now(): number;
  /** Deliver `frames` animation frames, `frameMs` apart. */
  runFrames(frames: number, frameMs?: number): void;
  /** Deliver frames until at least `ms` of fake time has elapsed. */
  runFor(ms: number, frameMs?: number): void;
  /**
   * Advance the wall clock WITHOUT delivering any frame — what a browser does
   * to a hidden tab (rAF callbacks are not dispatched while hidden, and the
   * first frame after the tab returns carries the current timestamp).
   */
  suspend(ms: number): void;
  /** Number of frames delivered so far. */
  readonly frameCount: number;
  restore(): void;
}

export function createFrameClock(startMs = 1_000): FrameClock {
  let current = startMs;
  let frameCount = 0;
  let nextId = 1;
  let pending = new Map<number, FrameRequestCallback>();

  const originals = {
    requestAnimationFrame: globalThis.requestAnimationFrame,
    cancelAnimationFrame: globalThis.cancelAnimationFrame,
    performanceNow: globalThis.performance?.now,
  };

  globalThis.requestAnimationFrame = ((cb: FrameRequestCallback): number => {
    const id = nextId++;
    pending.set(id, cb);
    return id;
  }) as typeof globalThis.requestAnimationFrame;

  globalThis.cancelAnimationFrame = ((id: number): void => {
    pending.delete(id);
  }) as typeof globalThis.cancelAnimationFrame;

  if (globalThis.performance) {
    globalThis.performance.now = () => current;
  }

  function deliverOneFrame(frameMs: number): void {
    current += frameMs;
    const due = pending;
    pending = new Map();
    frameCount += 1;
    for (const cb of due.values()) cb(current);
  }

  return {
    now: () => current,
    get frameCount() {
      return frameCount;
    },
    runFrames(frames: number, frameMs = 1000 / 60) {
      for (let i = 0; i < frames; i++) deliverOneFrame(frameMs);
    },
    runFor(ms: number, frameMs = 1000 / 60) {
      const target = current + ms;
      while (current < target) deliverOneFrame(frameMs);
    },
    suspend(ms: number) {
      current += ms;
    },
    restore() {
      globalThis.requestAnimationFrame = originals.requestAnimationFrame;
      globalThis.cancelAnimationFrame = originals.cancelAnimationFrame;
      if (globalThis.performance && originals.performanceNow) {
        globalThis.performance.now = originals.performanceNow;
      }
    },
  };
}
