import { t } from "$lib/shared/i18n/i18n.svelte";
import type { GuideBlock } from "./guide-content-blocks";

// The source content remains Austen's English proof copy. Translate at render
// time so the print sheet and reflow view react to a locale change together.
const keyByText = {
  "The Grid": "verified_level1_the_grid",
  "The Kinetic Alphabet is based on a 4-point grid.": "verified_level1_grid_intro",
  "The Kinetic Alphabet is based on a 4-point grid.<br><br>There are two 4-point grids: box mode and diamond mode.<br><strong>This guide is written in diamond, but everything translates to box.</strong><br><br>On this grid, there are three types of points:": "verified_level1_grid_sheet_intro",
  "There are two 4-point grids: box mode and diamond mode.<br><strong>This guide is written in diamond, but everything translates to box.</strong><br><br>On this grid, there are three types of points:": "verified_level1_grid_overview",
  "Two hands on the diamond grid: blue at west, red at east.": "verified_level1_grid_hands_caption",
  "The <strong>center point</strong> is the hub that<br>everything revolves around.<br><br>The four <strong>hand points</strong> are halfway<br>between the center point and the<br>outer points.<br><br>The <strong>outer points</strong> depict the outer<br>edges of the grid.": "verified_level1_grid_points",
  "Together, diamond and box form an 8-point grid:": "verified_level1_grid_combination",
  "Diamond": "verified_level1_diamond",
  "Box": "verified_level1_box",
  "8-point grid": "verified_level1_eight_point_grid",
  "Diamond grid: four points at north, east, south, and west": "verified_level1_diamond_aria",
  "Box grid: four points on the diagonals": "verified_level1_box_aria",
  "8-point grid: diamond and box combined": "verified_level1_eight_point_aria",
  "We’ll use diamond mode to learn each concept.": "verified_level1_grid_closing",
  "hand": "verified_level1_hand",
  "points": "verified_level1_points",
  "center": "verified_level1_center",
  "point": "verified_level1_point",
  "outer": "verified_level1_outer",
  "Hand Placements": "verified_level1_hand_placements",
  "There are multiple ways to combine two hand points to form a hand placement.<br>Placements can be rotated or mirrored.<span class=\"lg\"></span><strong><span class=\"cR\">Red = Right</span> and <span class=\"cB\">Blue = Left.</span></strong><br>In The Kinetic Alphabet, our first three placements are called Alpha, Beta, and Gamma.": "verified_level1_placements_intro",
  "In Alpha, the hands occupy the points across from each other.": "verified_level1_alpha_definition",
  "In Beta, the hands occupy the same point.": "verified_level1_beta_definition",
  "In Gamma, the hands form a right angle.": "verified_level1_gamma_definition",
  "Base Letters": "verified_level1_base_letters_1",
  "Type 1 - Dual-Shift": "verified_level1_base_letters_2",
  "Just like positions, each motion pictograph can be rotated, reflected, or color swapped.<br>Letters are organized on the page by end position, Alpha, Beta, then Gamma.<br>Let’s look at each type individually.": "verified_level1_base_letters_3",
  "First we’ll look at A, B, and C. Their handpath is <em>Split-Same</em> and they move from α→α:": "verified_level1_base_letters_4",
  "A · B · C: α→α Split-Same": "verified_level1_base_letters_5",
  "Notice the pattern: <strong>Pro - Anti - Hybrid</strong><br>This pattern helps you navigate/memorize the letters.": "verified_level1_base_letters_6",
  "If you only remember that A has prospins, you can infer that B has antispins.<br>If you only remember that B has antispins, you can infer that C is a hybrid.<br><strong><em>If you memorize only one letter in each group, you know all of them.</em></strong>": "verified_level1_base_letters_7",
  "Next let’s look at G, H, and I. Their handpaths are <em>Tog-Same</em> and they move from β→β:": "verified_level1_base_letters_8",
  "G · H · I: β→β Tog-Same": "verified_level1_base_letters_9",
  "In hybrids like C and I, either hand can execute a prospin or antispin.": "verified_level1_base_letters_10",
  "Here, the <strong class=\"cR\">right</strong> is in pro and <strong class=\"cB\">left</strong> in anti, but it’s equally valid to swap this.": "verified_level1_base_letters_11",
  "The Codex, Continued": "verified_level1_codex_2_12",
  "Type 3: Cross-Shift": "verified_level1_codex_2_13",
  "Type 4: Dash": "verified_level1_codex_2_14",
  "Type 5: Dual-Dash": "verified_level1_codex_2_15",
  "Type 6: Static": "verified_level1_codex_2_16",
  "The Codex": "verified_level1_codex_17",
  "Double Staff": "verified_level1_codex_18",
  "Type 1: Dual-Shift": "verified_level1_codex_19",
  "Type 2: Shift": "verified_level1_codex_20",
  "8-Letter Words": "verified_level1_eight_letter_words_21",
  "Words can be any length.<br>These 8-letter words repeat twice, to create 16-count sequences.": "verified_level1_eight_letter_words_22",
  "IIΩXKEΣY": "verified_level1_eight_letter_words_23",
  "(Rotated LOOP)": "verified_level1_eight_letter_words_24",
  "CΣNZIΘUW": "verified_level1_eight_letter_words_25",
  "(Mirrored + Swapped LOOP)": "verified_level1_eight_letter_words_26",
  "Examples": "verified_level1_examples_abc_27",
  "Let’s practice reversals and permutations.<br>We’ll use AABB as an example to explore different reversal placements.<br><strong>These start from the same alpha start position. Interpret it from the first motions.</strong>": "verified_level1_examples_abc_28",
  "Here’s an AABB in which both staves execute <strong>prop-reversals</strong> after steps 2 and 4, notated by an “<strong class=\"cR\">R</strong>/<strong class=\"cB\">R</strong>” on the pictographs.": "verified_level1_examples_abc_29",
  "This requires negative space or a body turn to execute.": "verified_level1_examples_abc_30",
  "Let’s place the reversals in a different place. This time we’ll put them after step 1.": "verified_level1_examples_abc_31",
  "This will put our left hand on top after step 4, so we’ll repeat the sequence again mirrored (with a reversal after step 5) to return to our original home position.": "verified_level1_examples_abc_32",
  "This is a <em>Mirrored LOOP</em>.": "verified_level1_examples_abc_33",
  "Now let’s look at another variation of AABB*2 with reversals after steps 3 & 7:": "verified_level1_examples_abc_34",
  "As demonstrated with these examples, a reversal in different locations in the word can lead to a notably different outcome.": "verified_level1_examples_abc_35",
  "The word AABB is not limited to one presentation, it is a broad category of sequences that includes those letters with variations on reversals and thumb orientation.": "verified_level1_examples_abc_36",
  "Mixed Words: ACAC and BCBC": "verified_level1_examples_acac_37",
  "When combining a hybrid like C with a non-hybrid like A or B, a prop-reversal is necessary.<br>Let’s look at the word ACAC.": "verified_level1_examples_acac_38",
  "In this variation, the left hand does a reversal on every step. Give it a try:": "verified_level1_examples_acac_39",
  "Start": "verified_level1_examples_acac_40",
  "1": "verified_level1_examples_acac_41",
  "2": "verified_level1_examples_acac_42",
  "3": "verified_level1_examples_acac_43",
  "4": "verified_level1_examples_acac_44",
  "It would be impossible to execute ACAC without using a prop-reversal.": "verified_level1_examples_acac_45",
  "The previous example shows the hands moving in a <em>continuous</em> path.<br>Let’s change that in the next example by including a full-reversal in the middle.<br>In this example, the reversals alternate between left (<strong class=\"cB\">R</strong>) and right (<strong class=\"cR\">R</strong>).": "verified_level1_examples_acac_46",
  "This example uses every type of reversal - <em>hand</em>, <em>prop</em>, and <em>full</em>.<br>Challenge yourself to identify where each one occurs.": "verified_level1_examples_acac_47",
  "Prop-reversals are also required with BCBC, as shown in this example:": "verified_level1_examples_acac_48",
  "Here, the <strong class=\"cR\">right</strong> hand is prop-reversing after every step. Eventually, it returns to home.": "verified_level1_examples_acac_49",
  "Hand-reversal": "verified_level1_examples_cccc_50",
  "Prop-reversal": "verified_level1_examples_cccc_51",
  "Full-reversal": "verified_level1_examples_cccc_52",
  "Hybrid Reversals: CCCC": "verified_level1_examples_cccc_53",
  "Let’s add reversals after the second B.": "verified_level1_examples_cccc_54",
  "Take note - step 5 has the right hand coming down on the left side of the grid, so it’s impossible to follow through to step 6 while remaining square with the audience in wall plane. We must <em>body turn</em> on step 5. If turning left, we can bring the left staff into the plane behind us as it comes up, moving our relative position into wheel plane.": "verified_level1_examples_cccc_55",
  "This sequence is a good example of how body turns can serve both as a method of motion execution and a body movement that can add energy and contrast.": "verified_level1_examples_cccc_56",
  "Now let’s observe how reversals affect pro/anti hybrid words like CCCC.<br>They present more variations than non-hybrids:": "verified_level1_examples_cccc_57",
  "Full-Reversal LOOPs": "verified_level1_full_reversal_loops_58",
  "Each of these words uses a full-reversal.<br>There are also prop-reversals within these words.<br>Challenge yourself to identify each one.": "verified_level1_full_reversal_loops_59",
  "CCKE": "verified_level1_full_reversal_loops_60",
  "FLII": "verified_level1_full_reversal_loops_61",
  "DAK": "verified_level1_full_reversal_loops_62",
  "Gamma LOOPs": "verified_level1_gamma_loops_63",
  "<strong>The γ→γ letters can connect to any other γ→γ letter.</strong><br>In these examples, each word ends in gamma position on the opposite side.<br>By repeating the word from there, we return to home position.": "verified_level1_gamma_loops_64",
  "Rotated": "verified_level1_gamma_loops_65",
  "SOTR is the print example for this slot: a Rotated LOOP that never leaves gamma.": "verified_level1_gamma_loops_66",
  "VPUQ is the print example for this slot: a Rotated LOOP that never leaves gamma.": "verified_level1_gamma_loops_67",
  "MVNU is the print example for this slot: a Rotated LOOP that never leaves gamma.": "verified_level1_gamma_loops_68",
  "Note that the pictographs in each second word repetition are rotated 180°.<br>Because of this, these examples are classified as <em>Rotated LOOPs</em>.": "verified_level1_gamma_loops_69",
  "Static": "verified_level1_hand_motions_70",
  "Hand Motions": "verified_level1_hand_motions_71",
  "There are three fundamental hand motions in the Alphabet.<br>The arrow shows the direction of motion.<br>The hand shows the end position.": "verified_level1_hand_motions_72",
  "Move to an<br>adjacent point": "verified_level1_hand_motions_73",
  "Move to the<br>opposite point": "verified_level1_hand_motions_74",
  "Stay at the<br>current point": "verified_level1_hand_motions_75",
  "Using these, we can derive six combinations, named below.<br>We’ll explore each one individually:": "verified_level1_hand_motions_76",
  "Dual-Shift": "verified_level1_hand_motions_77",
  "Both hands travel to an adjacent point.": "verified_level1_hand_motions_78",
  "Shift": "verified_level1_hand_motions_79",
  "One hand travels to an adjacent point<br>and the other hand remains static.": "verified_level1_hand_motions_80",
  "Cross-Shift": "verified_level1_hand_motions_81",
  "One hand travels to an adjacent point and<br>the other travels to the opposite point.": "verified_level1_hand_motions_82",
  "Dash": "verified_level1_hand_motions_83",
  "One hand travels to the opposite point<br>and the other hand remains static": "verified_level1_hand_motions_84",
  "Dual-Dash": "verified_level1_hand_motions_85",
  "Both hands travel to the opposite point": "verified_level1_hand_motions_86",
  "Both hands remain static.": "verified_level1_hand_motions_87",
  "Alpha (α)": "verified_level1_hand_placements_88",
  "Alpha": "verified_level1_hand_placements_89",
  "Beta (β)": "verified_level1_hand_placements_90",
  "Beta": "verified_level1_hand_placements_91",
  "Gamma (γ)": "verified_level1_hand_placements_92",
  "Gamma": "verified_level1_hand_placements_93",
  "Gamma: Quarter-Opposite and Quarter-Same": "verified_level1_hm_gamma_94",
  "Gamma, aka quarter-time, is based on two often forgotten modes:<br><strong>Quarter-Opp</strong> and <strong>Quarter-Same</strong>.<br>Quarter-Opp has variations of parallel and antiparallel.": "verified_level1_hm_gamma_95",
  "Quarter-Opp": "verified_level1_hm_gamma_96",
  "γ→γ Quarter-Opp": "verified_level1_hm_gamma_97",
  "In Quarter-Same, this doesn’t happen:": "verified_level1_hm_gamma_98",
  "Quarter-Same": "verified_level1_hm_gamma_99",
  "γ→γ Quarter-Same": "verified_level1_hm_gamma_100",
  "When in gamma, you can move to any other variation of gamma.<br>These examples are continuous, but non-continuous sequence are also possible.": "verified_level1_hm_gamma_101",
  "Here’s one that switches between Quarter-Opp and Quarter-Same:": "verified_level1_hm_gamma_102",
  "Quarter-Opp / Same switch": "verified_level1_hm_gamma_103",
  "<strong>Practice using <span class=\"cy\">Dual</span><span class=\"pu\">-Shifts</span> to create other non-continuous γ→γ variations!</strong>": "verified_level1_hm_gamma_104",
  "Type 1 Dual-Shifts: Alpha and Beta": "verified_level1_hm_type1_105",
  "When both hands move to adjacent locations, it’s called a <span class=\"cy\">Dual</span><span class=\"pu\">-Shift</span>.<br>Our first <span class=\"cy\">Dual</span><span class=\"pu\">-Shifts</span> correspond to the four modes of time/direction: SS, TS, SO, TO.<br>You can determine the start position by looking at the non-pointed end of the arrow.": "verified_level1_hm_type1_106",
  "Split-Same": "verified_level1_hm_type1_107",
  "Tog-Same": "verified_level1_hm_type1_108",
  "The Kinetic Alphabet puts focus on simultaneous motions between<br>two positions, relative to the center point.<br>Let’s try another type of <span class=\"cy\">Dual</span><span class=\"pu\">-Shift</span>.<br>What happens when we move between α and β?": "verified_level1_hm_type1_109",
  "Split-Opp": "verified_level1_hm_type1_110",
  "Tog-Opp": "verified_level1_hm_type1_111",
  "Notice that it can be either <em>Split-Opp</em> or <em>Tog-Opp</em> depending on start position.": "verified_level1_hm_type1_112",
  "<strong>Practice using <span class=\"cy\">Dual</span><span class=\"pu\">-Shifts</span> to travel between Alpha and Beta in each mode.</strong>": "verified_level1_hm_type1_113",
  "Type 2 Shifts": "verified_level1_hm_type2_114",
  "To move between γ and α/β, you can shift one hand and keep the other hand static.<br>This combination is called a <strong class=\"pu\">Shift</strong> (with a capital “S”). Here’s a simple example:": "verified_level1_hm_type2_115",
  "The following examples explore both same and opposite handpaths.<br>They alternate the shifting hand.<br>Here, they are shifting in the same direction:": "verified_level1_hm_type2_116",
  "And here, they are shifting in opposite directions.": "verified_level1_hm_type2_117",
  "<span class=\"pu\">Shifts</span> seems mundane here, but they’re very useful later for constructing dynamic sequences.": "verified_level1_hm_type2_118",
  "Type 3 Cross-Shifts": "verified_level1_hm_type34_119",
  "A <span class=\"cross\">Cross</span><span class=\"shift\">-Shift</span> combines a shift and a dash.<br>Since a dash has further to travel, it moves slightly faster.<br>To understand <span class=\"cross\">Cross</span><span class=\"shift\">-Shifts</span>, let’s break one down into parts:": "verified_level1_hm_type34_120",
  "start → halfway → end = combined": "verified_level1_hm_type34_121",
  "Note the halfway point. One hand is in the center point and one is on a diagonal hand point.<br>By pausing at this halfway point, it ensures that the dash moves at the correct speed.<br>The following sequences demonstrate their capabilities.<br>This one explores alpha → gamma:": "verified_level1_hm_type34_122",
  "α → γ": "verified_level1_hm_type34_123",
  "And this one shows beta → gamma:": "verified_level1_hm_type34_124",
  "β → γ": "verified_level1_hm_type34_125",
  "Tech nerds will notice these <span class=\"cross\">Cross</span><span class=\"shift\">-Shifts</span> create <em>Zan’s Diamond</em> variations. Neat!": "verified_level1_hm_type34_126",
  "Type 4, 5, 6: Dash, Dual-Dash, Static": "verified_level1_hm_type56_127",
  "Type 4 - Dash": "verified_level1_hm_type56_128",
  "With a <span class=\"k-dash\">Dash</span>, one hand executes a dash while the other hand remains static.<br>With alpha → beta, this creates a two-step sequence:": "verified_level1_hm_type56_129",
  "And with gamma → gamma, it creates a 4-step sequence:": "verified_level1_hm_type56_130",
  "Type 5 - Dual-Dash": "verified_level1_hm_type56_131",
  "With a <span class=\"k-dual\">Dual</span><span class=\"k-dash\">-Dash</span>, both hands dash simultaneously to their opposite points.": "verified_level1_hm_type56_132",
  "Practice using <span class=\"k-dual\">Dual</span><span class=\"k-dash\">-Dashes</span>, <span class=\"k-dash\">Dashes</span>, and <span class=\"k-cross\">Cross</span><span class=\"k-shift\">-Shifts</span><br>from different start positions.": "verified_level1_hm_type56_133",
  "Type 6 - Static": "verified_level1_hm_type56_134",
  "Finally, <span class=\"k-static\">Static</span> motions are indicated by no arrow:": "verified_level1_hm_type56_135",
  "Later on, static sequences gain complexity when adding prop rotations.": "verified_level1_hm_type56_136",
  "Alpha and Beta Words": "verified_level1_lt1_abc_ghi_137",
  "Same Direction": "verified_level1_lt1_abc_ghi_138",
  "The first words we will learn correspond to VTG’s 1:1 motions.<br>To execute these, <strong><em>you’ll need to use body turns and/or negative space</em></strong>.": "verified_level1_lt1_abc_ghi_139",
  "Practice each word once in both directions, then again starting with thumbs out.": "verified_level1_lt1_abc_ghi_140",
  "AAAA: α→α Split-Same": "verified_level1_lt1_abc_ghi_141",
  "BBBB: α→α Split-Same": "verified_level1_lt1_abc_ghi_142",
  "CCCC: α→α Split-Same": "verified_level1_lt1_abc_ghi_143",
  "GGGG: β→β Tog-Same": "verified_level1_lt1_abc_ghi_144",
  "HHHH: β→β Tog-Same": "verified_level1_lt1_abc_ghi_145",
  "IIII: β→β Tog-Same": "verified_level1_lt1_abc_ghi_146",
  "Compound Letters": "verified_level1_lt1_dj_ek_fl_147",
  "Now let’s look at the letters that move from β→α or α→β.": "verified_level1_lt1_dj_ek_fl_148",
  "All pictographs can be rotated or mirrored without changing letters.": "verified_level1_lt1_dj_ek_fl_149",
  "These can be either <em>Tog-Opp</em> or <em>Split-Opp</em> depending on which α/β you start from.": "verified_level1_lt1_dj_ek_fl_150",
  "D · E · F: β→α (Tog-Opp)": "verified_level1_lt1_dj_ek_fl_151",
  "J · K · L: α→β (Tog-Opp)": "verified_level1_lt1_dj_ek_fl_152",
  "D · E · F: β→α (Split-Opp)": "verified_level1_lt1_dj_ek_fl_153",
  "J · K · L: α→β (Split-Opp)": "verified_level1_lt1_dj_ek_fl_154",
  "These compound letters can’t be self-combined like the previous letters.": "verified_level1_lt1_dj_ek_fl_155",
  "Instead, they combine with other compound letters to form the words DJ, EK, and FL.": "verified_level1_lt1_dj_ek_fl_156",
  "Here they are along with cute phrases to help you remember:": "verified_level1_lt1_dj_ek_fl_157",
  "DJ: Disco Jam": "verified_level1_lt1_dj_ek_fl_158",
  "<span class=\"tka-font\">DJ</span> - <em>Disco Jam</em>": "verified_level1_lt1_dj_ek_fl_159",
  "EK: Exploding Kitten": "verified_level1_lt1_dj_ek_fl_160",
  "<span class=\"tka-font\">EK</span> - <em>Exploding Kitten</em>": "verified_level1_lt1_dj_ek_fl_161",
  "FL: Fruity Loops": "verified_level1_lt1_dj_ek_fl_162",
  "<span class=\"tka-font\">FL</span> - <em>Fruity Loops</em>": "verified_level1_lt1_dj_ek_fl_163",
  "Gamma Words": "verified_level1_lt1_gamma_words_164",
  "These are the simplest 4-letter words created with continuous γ→γ motions:": "verified_level1_lt1_gamma_words_165",
  "MPMP: γ→γ (Opp)": "verified_level1_lt1_gamma_words_166",
  "NQNQ: γ→γ (Opp)": "verified_level1_lt1_gamma_words_167",
  "OROR: γ→γ (Opp)": "verified_level1_lt1_gamma_words_168",
  "SSSS: γ→γ (Same)": "verified_level1_lt1_gamma_words_169",
  "TTTT: γ→γ (Same)": "verified_level1_lt1_gamma_words_170",
  "UUUU: γ→γ (Same)": "verified_level1_lt1_gamma_words_171",
  "VVVV: γ→γ (Same)": "verified_level1_lt1_gamma_words_172",
  "Gamma Letters": "verified_level1_lt1_mp_nq_or_stuv_173",
  "γ→γ motions can combine with any other γ→γ motion to create lots of words!<br>First let’s look at the compound letters (<em>Quarter-Opp</em>).": "verified_level1_lt1_mp_nq_or_stuv_174",
  "M · N · O: γ→γ Quarter-Opp": "verified_level1_lt1_mp_nq_or_stuv_175",
  "P · Q · R: γ→γ Quarter-Opp": "verified_level1_lt1_mp_nq_or_stuv_176",
  "When combined as a continuous motion, these form MP, NQ, and OR.<br>Here they are along with a memorable phrase:": "verified_level1_lt1_mp_nq_or_stuv_177",
  "MP: Magic Potion": "verified_level1_lt1_mp_nq_or_stuv_178",
  "<span class=\"tka-font\">MP</span> - <em>Magic Potion</em>": "verified_level1_lt1_mp_nq_or_stuv_179",
  "NQ: Never Quit": "verified_level1_lt1_mp_nq_or_stuv_180",
  "<span class=\"tka-font\">NQ</span> - <em>Never Quit</em>": "verified_level1_lt1_mp_nq_or_stuv_181",
  "OR: Open Road": "verified_level1_lt1_mp_nq_or_stuv_182",
  "<span class=\"tka-font\">OR</span> - <em>Open Road</em>": "verified_level1_lt1_mp_nq_or_stuv_183",
  "The final γ→γ group (<em>Quarter-Same</em>) has 4 instead of 3.<br>It may seem like U and V contain the same information, but it’s impossible to rotate or<br>reflect U in order to turn it into V, and vice-versa, so they must be disambiguated.": "verified_level1_lt1_mp_nq_or_stuv_184",
  "S · T · U · V: γ→γ Quarter-Same": "verified_level1_lt1_mp_nq_or_stuv_185",
  "Note that all four have a <em>leading</em> hand and a <em>following</em> hand.<br>Here, the <strong class=\"cR\">right</strong> is leading and <strong class=\"cB\">left</strong> is following, but it’s equally valid to swap this.<br><strong><em>U leads with an isolation</em></strong> (a round motion like the letter U).<br><strong><em>V leads with an antispin</em></strong> (a spiky motion like the letter V).<br>These self-combine to form the words SS, TT, UU, and VV.": "verified_level1_lt1_mp_nq_or_stuv_186",
  "γ→α": "verified_level1_lt2_wxyz_187",
  "γ→β": "verified_level1_lt2_wxyz_188",
  "α→γ": "verified_level1_lt2_wxyz_189",
  "β→γ": "verified_level1_lt2_wxyz_190",
  "Type 2 Shift Letters": "verified_level1_lt2_wxyz_191",
  "So far we’ve learned how to move between α↔β and between γ↔γ.<br>In order to travel between these two modes, we can use a Type 2 Motion called a <strong style=\"color:#6F2DA8\">Shift</strong>.": "verified_level1_lt2_wxyz_192",
  "<strong>A <span style=\"color:#6F2DA8\">Shift</span> (or single shift) is the combination of one shift and one static motion.</strong><br>Their letters are organized by end position: α, β, then γ.<br>These can also be categorized by opening or closing.": "verified_level1_lt2_wxyz_193",
  "γ→α OPEN: W, X": "verified_level1_lt2_wxyz_194",
  "γ→β CLOSE: Y, Z": "verified_level1_lt2_wxyz_195",
  "α→γ CLOSE: Sigma, Delta": "verified_level1_lt2_wxyz_196",
  "β→γ OPEN: Theta, Omega": "verified_level1_lt2_wxyz_197",
  "When we arrange them in continuous motions, we get the words WΣYΘ and XΔZΩ.": "verified_level1_lt2_wxyz_198",
  "WΣYΘ: pro": "verified_level1_lt2_wxyz_199",
  "XΔZΩ: anti": "verified_level1_lt2_wxyz_200",
  "Though simple at this stage, these motions become more complex<br>as we dive deeper into the Alphabet and add rotations to static motions.": "verified_level1_lt2_wxyz_201",
  "Type 3 Cross-Shift Letters": "verified_level1_lt3_dash_letters_202",
  "<strong style=\"color:#26e600\">Cross</strong><strong style=\"color:#6F2DA8\">-Shifts</strong> use the same letters as <strong style=\"color:#6F2DA8\">Shifts</strong>, but each letter is followed by a<br>dash to indicate that the other hand is dashing into its end position.<br>They are spoken as “W Dash” or “Sigma Dash”.<br><em>A dash symbol in the glyph equals a dash arrow on the graph.</em><br><strong><em>The end position for each Type 2/3 letter remains the same.</em></strong>": "verified_level1_lt3_dash_letters_203",
  "γ→α: W-, X-": "verified_level1_lt3_dash_letters_204",
  "γ→β: Y-, Z-": "verified_level1_lt3_dash_letters_205",
  "β→γ: Sig Dash, Del Dash": "verified_level1_lt3_dash_letters_206",
  "α→γ: The Dash, Om Dash": "verified_level1_lt3_dash_letters_207",
  "<strong style=\"color:#26e600\">Cross</strong><strong style=\"color:#6F2DA8\">-Shifts</strong> can be tricky to remember. It helps to first picture the corresponding<br>Type 2 pictograph, then add the dash arrow without changing any other variables.": "verified_level1_lt3_dash_letters_208",
  "Just like we did with hands, let’s break down some <strong style=\"color:#26e600\">Cross</strong><strong style=\"color:#6F2DA8\">-Shifts</strong> step-by-step.": "verified_level1_lt3_dash_letters_209",
  "W-: step by step": "verified_level1_lt3_dash_letters_210",
  "Δ-: step by step": "verified_level1_lt3_dash_letters_211",
  "<strong><em>When initially learning, it’s useful to pause at the halfway point to ensure proper timing.</em></strong>": "verified_level1_lt3_dash_letters_212",
  "Type 4, 5, 6 Letters: Phi, Psi, Lambda": "verified_level1_lt456_phi_psi_lambda_213",
  "Phi, Psi, Lambda": "verified_level1_lt456_phi_psi_lambda_214",
  "With a <strong style=\"color:#26e600\">Dash</strong>, one prop executes a dash and the other remains static.<br><br>“Lambda” can be further shortened by calling it “Lam”.": "verified_level1_lt456_phi_psi_lambda_215",
  "Phi Dash, Psi Dash, Lam Dash": "verified_level1_lt456_phi_psi_lambda_216",
  "In a <strong style=\"color:#00b3ff\">Dual</strong><strong style=\"color:#26e600\">-Dash</strong>, both hands are dashing.<br>The end position remains the same.": "verified_level1_lt456_phi_psi_lambda_217",
  "Alpha, Beta, Gamma": "verified_level1_lt456_phi_psi_lambda_218",
  "In a <strong style=\"color:#eb7d00\">Static</strong> motion, both hands remain still for a beat.<br>These become more interesting when adding turns.": "verified_level1_lt456_phi_psi_lambda_219",
  "Type 1 LOOPs": "verified_level1_misc_permutations_220",
  "Mirrored": "verified_level1_misc_permutations_221",
  "In this example of DJII, the graphs in the second repetition (steps 5-8) mirror the graphs in the first repetition (steps 1-4), classifying it as a Mirrored LOOP.": "verified_level1_misc_permutations_222",
  "Swapped & Rotated LOOP": "verified_level1_misc_permutations_223",
  "Swapped & Rotated": "verified_level1_misc_permutations_224",
  "BBLF is the print example for this slot: a Swapped & Rotated LOOP.": "verified_level1_misc_permutations_225",
  "Swapped & Mirrored": "verified_level1_misc_permutations_226",
  "In this example of KIEC, the colors are swapped in the second half, so it is classified as a Swapped & Mirrored LOOP.": "verified_level1_misc_permutations_227",
  "In this example of DJII, the graphs in the second repetition (steps 5-8) mirror the<br>graphs in the first repetition (steps 1-4), classifying it as a <em>Mirrored LOOP</em>.": "verified_level1_print_type1_loops_djii",
  "In this example of KIEC, the colors are swapped in the second half,<br>so it is classified as a <em>Swapped & Mirrored LOOP</em>.": "verified_level1_print_type1_loops_kiec",
  "Type 1 - ": "verified_level1_print_type_1",
  "Type 2 - ": "verified_level1_print_type_2",
  "Type 3 - ": "verified_level1_print_type_3",
  "Thumbs": "verified_level1_print_thumbs",
  "Thumbs:": "verified_level1_print_thumbs_colon",
  "in": "verified_level1_print_in",
  "out": "verified_level1_print_out",
  "<span class=\"cB\">(out</span>/<span class=\"cR\">in)</span>": "verified_level1_print_out_in",
  "<span class=\"cB\">(in</span>/<span class=\"cR\">out)</span>": "verified_level1_print_in_out",
  "Negative Space and Body Turns": "verified_level1_negative_space_228",
  "Many sequences seem impossible, but most can be solved by using negative space or body turns.<br><strong><em>Negative space</em></strong> lets you face the audience and reduces body movement<br><strong><em>Body turns</em></strong> add movement and help you execute patterns with longer staves.<br>Each method is equally important, and learning both will maximize capability.<br>This guide will assume some knowledge of these fundamental concepts.": "verified_level1_negative_space_229",
  "To make the most of the Alphabet, it’s highly recommended that you learn the following.": "verified_level1_negative_space_230",
  "360° Isolation": "verified_level1_negative_space_231",
  "Start + steps 1–4": "verified_level1_negative_space_232",
  "To execute this without finger-spinning, turn your torso to the left on step 3. During this step, the staff moves briefly in wheel-plane relative to your left-facing view. On step 4, turn your body back to center as you return to the start position.": "verified_level1_negative_space_233",
  "Practice in reverse, then do both directions in the other hand.<br>Then practice it with the thumb out, isolating the pinky end.": "verified_level1_negative_space_234",
  "4-Petal Antispin": "verified_level1_negative_space_235",
  "To execute this in wall plane, you must do one of the following on step 2:": "verified_level1_negative_space_236",
  "• Pass the thumb end through the negative space above your right shoulder on step 2.<br>• Turn your torso to the left on step 2 and pass the thumb end in front, then pass the pinky end on the inside of your right arm as you move to step 3.": "verified_level1_negative_space_237",
  "Practice in reverse, then do both directions in the other hand.<br>Then practice everything again starting with the thumb out.<br>Try using both negative space and turns. Good luck!": "verified_level1_negative_space_238",
  "LOOPs": "verified_level1_permutations_239",
  "When a word ends on a variation of its start position, we can repeat it to trace a<br>complimentary pattern, eventually returning back to the start position (aka home).<br>This type of sequence is called a <strong><em>LOOP</em></strong>.": "verified_level1_permutations_240",
  "Three common types of LOOPs are <em>Mirrored</em>, <em>Rotated</em>, and <em>Swapped</em>.": "verified_level1_permutations_241",
  "In a mirrored LOOP, the second repetition’s pictographs reflect the first, which changes their rotation direction.": "verified_level1_permutations_242",
  "In this example, each column is reflected across a horizontal plane.": "verified_level1_permutations_243",
  "In a rotated LOOP, each repetition ends in a rotated variation on its previous position.": "verified_level1_permutations_244",
  "Rotated 90°": "verified_level1_permutations_245",
  "In this example, there is a 90° rotation, finally returning to the start position (aka “home”).": "verified_level1_permutations_246",
  "Swapped": "verified_level1_permutations_247",
  "In a swapped LOOP, each repetition swaps the roles of <strong class=\"cR\">right</strong>/<strong class=\"cB\">left</strong>.": "verified_level1_permutations_248",
  "Though the prop’s shapes look the same, this swap changes the body motion significantly.": "verified_level1_permutations_249",
  "Prop-Reversal LOOPs": "verified_level1_prop_reversal_loops_250",
  "Each of these words uses a prop-reversal.<br>These examples are <em>Rotated LOOPs</em>.": "verified_level1_prop_reversal_loops_251",
  "EΣQY Rotated": "verified_level1_prop_reversal_loops_252",
  "TWKΘ Rotated": "verified_level1_prop_reversal_loops_253",
  "BΔMX Rotated": "verified_level1_prop_reversal_loops_254",
  "In this example of BΔMX, the <strong class=\"cR\">right</strong> hand stops on steps 2 and 4 before resuming its motion around the center point. Even when there is a step with no motion in<br>between, we can still mark the reversal with an “<strong class=\"cR\">R</strong>” to indicate the prop reversal.": "verified_level1_prop_reversal_loops_255",
  "Pro→Anti": "verified_level1_reversals_256",
  "Anti→Pro": "verified_level1_reversals_257",
  "Pro→Pro": "verified_level1_reversals_258",
  "Anti→Anti": "verified_level1_reversals_259",
  "Reversals": "verified_level1_reversals_260",
  "Reversals open up a huge number of possibilities!<br>There are three types of reversals:": "verified_level1_reversals_261",
  "With a hand reversal, the hand returns to the point it came from previously, without changing the prop’s direction of spin. Relative to the center point, this changes a prospin to an antispin and vice-versa.": "verified_level1_reversals_262",
  "This is the simplest and least disruptive reversal. We’ve already used it in the previous examples.": "verified_level1_reversals_263",
  "With a prop reversal, the hand continues to the next point while the prop reverses direction. This reversal also changes a prospin into an antispin and vice-versa.": "verified_level1_reversals_264",
  "Since a prop reversal is less intuitive, an “<strong class=\"cR\">R</strong>/<strong class=\"cB\">R</strong>” is shown in the corresponding color on the pictograph to indicate it.": "verified_level1_reversals_265",
  "With a full-reversal, the prop and hand retrace their paths and return to their previous position, as if going backwards in time.": "verified_level1_reversals_266",
  "Because this contains a prop reversal, the “<strong class=\"cR\">R</strong>/<strong class=\"cB\">R</strong>” draws attention to it. This succinctly indicates to the performer that something unusual is happening.": "verified_level1_reversals_267",
  "16-Count Sequences": "verified_level1_sixteen_count_268",
  "These 4-letter words repeat 4 times, giving us 16-count sequences.": "verified_level1_sixteen_count_269",
  "Here, each repetition of the word ends in a β that is 90° from its start. This means it will take 4 repetitions to return to home.": "verified_level1_sixteen_count_270",
  "<em>(Rotated + Swapped LOOP)</em>": "verified_level1_sixteen_count_271",
  "Here, the staves return to home after two word repetitions. To make it symmetrical, it repeats twice more, filling the rest of the quadrants.": "verified_level1_sixteen_count_272",
  "<em>(Rotated + Mirrored + Swapped LOOP)</em>": "verified_level1_sixteen_count_273",
  "Staff Motions": "verified_level1_staff_motions_274",
  "During a shift, a prop can rotate in one of two directions - Prospin or Antispin": "verified_level1_staff_motions_275",
  "Prospin": "verified_level1_staff_motions_276",
  "• <strong>Prospin</strong> - The prop rotates the same direction as the handpath<br>A 90 degree isolation is our base unit of a prospin.": "verified_level1_staff_motions_277",
  "start · end · combined": "verified_level1_staff_motions_278",
  "In a base isolation, the thumb orientation remains the same for the entire motion.": "verified_level1_staff_motions_279",
  "Antispin": "verified_level1_staff_motions_280",
  "• <strong>Antispin</strong> - The prop rotates in the opposite direction of the handpath<br>A 90 degree antispin is our base unit of antispin.": "verified_level1_staff_motions_281",
  "In an antispin, the ends swap orientation. Here, it moves from thumb in to thumb out.": "verified_level1_staff_motions_282",
  "In a base dash, the thumb ends also swap orientation.": "verified_level1_staff_motions_283",
  "Halfway through the motion, the center of the staff is at the grid’s center point.": "verified_level1_staff_motions_284",
  "Staff Placements": "verified_level1_staff_placements_285",
  "When writing sequences with staves, it helps to mark the thumb end with a line.<br>The performer can use it to keep track of rotations and check their position on every step.<br>It also encourages negative space/body turns instead of finger spinning.": "verified_level1_staff_placements_286",
  "In the following examples, an end is always at the center point.": "verified_level1_staff_placements_287",
  "Practice each placement below, paying attention to the thumb orientation.": "verified_level1_staff_placements_288",
  "Thumbs: in out <span class=\"cB\">(out</span>/<span class=\"cR\">in)</span> <span class=\"cB\">(in</span>/<span class=\"cR\">out)</span>": "verified_level1_staff_placements_289",
  "Many of the pictographs in this guide are depicted with no thumb ends<br>when categorizing. It is usually noted only during sequences.": "verified_level1_staff_placements_290",
  "Most sequences in this guide start with thumbs in for consistency.<br>It’s equally valid to start any sequence from a different thumb orientation.": "verified_level1_staff_placements_291",
  "Type 2 LOOPs": "verified_level1_type2_loops_292",
  "These words use the Type 2 letters to travel between α/β and γ.": "verified_level1_type2_loops_293",
  "Since each repetition is rotated by 180°, these are all <em>Rotated LOOPs</em>.": "verified_level1_type2_loops_294",
  "BΣTX is the print example for this slot: a Rotated LOOP that travels between alpha and gamma.": "verified_level1_type2_loops_295",
  "EΔUZ is the print example for this slot: a Rotated LOOP that travels between beta and gamma.": "verified_level1_type2_loops_296",
  "OYHΘ is the print example for this slot: a Rotated LOOP that travels between gamma and beta.": "verified_level1_type2_loops_297",
  "in | in": "verified_level1_words_298",
  "out | out": "verified_level1_words_299",
  "in | out": "verified_level1_words_300",
  "Words": "verified_level1_words_301",
  "Let’s create more complex words using pictographs!": "verified_level1_words_302",
  "In order to perform the words in this section correctly without finger-spinning,<br>you must be familiar with negative space and body turns.": "verified_level1_words_303",
  "If you finger-spin instead of using negative space, you’ll lose precision and<br>the ability to check your thumb orientation on each step to see if you’re still on track.": "verified_level1_words_304",
  "We’ll use the word AABB as an example. Here are three variations on AABB, starting from<br>different thumb orientations. Use staves or <strong><span class=\"cR\">red</span>/<span class=\"cB\">blue</span></strong> pens to follow along.": "verified_level1_words_305",
  "AABB: thumbs in | in": "verified_level1_words_306",
  "AABB: thumbs out | out": "verified_level1_words_307",
  "AABB: thumbs in | out": "verified_level1_words_308",
  "As you execute these with staves, notice that each of these sequences requires a different type<br>of negative space, either above/below the shoulder or behind the elbow.": "verified_level1_words_309",
  "The execution of the same word can feel completely different depending on factors like<br>the start position, rotation direction, and thumb orientation. That’s why it’s necessary to<br>draw the full sequence with pictographs for complete clarity.": "verified_level1_words_310",
  "<strong>The Alphabet is primarily a system of <em>pictographs</em>,<br>organized by letters for convenient communication.</strong>": "verified_level1_words_311",
  "The letters do not give all of the information, and are merely intended to separate<br>motion combinations into categories which can be further clarified with detailed pictographs.": "verified_level1_words_312",
  "Flow Arts Placements: Alpha, Beta, Gamma": "verified_level1_guide_page_seo_1",
  "The three starting hand placements in The Kinetic Alphabet.": "verified_level1_guide_page_seo_2",
  "Flow Arts Placements: Alpha, Beta, Gamma · The Kinetic Alphabet": "verified_level1_guide_page_seo_3",
  "The three starting hand placements in The Kinetic Alphabet notation. In Alpha the hands occupy the points across from each other; in Beta the same point; in Gamma they form a right angle.": "verified_level1_guide_page_seo_4",
  "The Grid · Flow Arts Notation Guide": "verified_level1_guide_page_seo_5",
  "There are three fundamental hand motions in the Alphabet.": "verified_level1_guide_page_seo_6",
  "Hand Motions: Shift, Dash, Static · Flow Arts Notation Guide": "verified_level1_guide_page_seo_7",
  "When both hands move to adjacent locations, it’s called a Dual-Shift.": "verified_level1_guide_page_seo_8",
  "Type 1 Dual-Shifts: Alpha and Beta · Flow Arts Notation Guide": "verified_level1_guide_page_seo_9",
  "Gamma, aka quarter-time, is based on two often forgotten modes: Quarter-Opp and Quarter-Same.": "verified_level1_guide_page_seo_10",
  "Gamma: Quarter-Opposite and Quarter-Same · Flow Arts Notation Guide": "verified_level1_guide_page_seo_11",
  "To move between γ and α/β, you can shift one hand and keep the other hand static.": "verified_level1_guide_page_seo_12",
  "Type 2 Shifts · Flow Arts Notation Guide": "verified_level1_guide_page_seo_13",
  "A Cross-Shift combines a shift and a dash.": "verified_level1_guide_page_seo_14",
  "Type 3 Cross-Shifts · Flow Arts Notation Guide": "verified_level1_guide_page_seo_15",
  "With a Dash, one hand executes a dash while the other hand remains static.": "verified_level1_guide_page_seo_16",
  "Type 4, 5, 6: Dash, Dual-Dash, Static · Flow Arts Notation Guide": "verified_level1_guide_page_seo_17",
  "When writing sequences with staves, it helps to mark the thumb end with a line.": "verified_level1_guide_page_seo_18",
  "Staff Placements · Flow Arts Notation Guide": "verified_level1_guide_page_seo_19",
  "Staff Motions: Prospin and Antispin · Flow Arts Notation Guide": "verified_level1_guide_page_seo_20",
  "Many sequences seem impossible, but most can be solved by using negative space or body turns.": "verified_level1_guide_page_seo_21",
  "Negative Space and Body Turns · Flow Arts Notation Guide": "verified_level1_guide_page_seo_22",
  "Just like positions, each motion pictograph can be rotated, reflected, or color swapped.": "verified_level1_guide_page_seo_23",
  "Base Letters · Flow Arts Notation Guide": "verified_level1_guide_page_seo_24",
  "The first words we will learn correspond to VTG’s 1:1 motions.": "verified_level1_guide_page_seo_25",
  "Alpha and Beta Words · Flow Arts Notation Guide": "verified_level1_guide_page_seo_26",
  "Compound Letters · Flow Arts Notation Guide": "verified_level1_guide_page_seo_27",
  "γ→γ motions can combine with any other γ→γ motion to create lots of words!": "verified_level1_guide_page_seo_28",
  "Gamma Letters · Flow Arts Notation Guide": "verified_level1_guide_page_seo_29",
  "These are the simplest 4-letter words created with continuous γ→γ motions.": "verified_level1_guide_page_seo_30",
  "Gamma Words · Flow Arts Notation Guide": "verified_level1_guide_page_seo_31",
  "So far we’ve learned how to move between α↔β and between γ↔γ.": "verified_level1_guide_page_seo_32",
  "Type 2 Shift Letters · Flow Arts Notation Guide": "verified_level1_guide_page_seo_33",
  "Cross-Shifts use the same letters as Shifts, but each letter is followed by a dash to indicate that the other hand is dashing into its end position.": "verified_level1_guide_page_seo_34",
  "Type 3 Cross-Shift Letters · Flow Arts Notation Guide": "verified_level1_guide_page_seo_35",
  "With a Dash, one prop executes a dash and the other remains static.": "verified_level1_guide_page_seo_36",
  "Type 4, 5, 6 Letters: Phi, Psi, Lambda · Flow Arts Notation Guide": "verified_level1_guide_page_seo_37",
  "Words · Flow Arts Notation Guide": "verified_level1_guide_page_seo_38",
  "Three common types of LOOPs are Mirrored, Rotated, and Swapped.": "verified_level1_guide_page_seo_39",
  "LOOPs · Flow Arts Notation Guide": "verified_level1_guide_page_seo_40",
  "Reversals open up a huge number of possibilities!": "verified_level1_guide_page_seo_41",
  "Reversals · Flow Arts Notation Guide": "verified_level1_guide_page_seo_42",
  "Let’s practice reversals and permutations.": "verified_level1_guide_page_seo_43",
  "Examples · Flow Arts Notation Guide": "verified_level1_guide_page_seo_44",
  "Hybrid Reversals: CCCC · Flow Arts Notation Guide": "verified_level1_guide_page_seo_45",
  "When combining a hybrid like C with a non-hybrid like A or B, a prop-reversal is necessary.": "verified_level1_guide_page_seo_46",
  "Mixed Words: ACAC and BCBC · Flow Arts Notation Guide": "verified_level1_guide_page_seo_47",
  "Type 1 LOOPs · Flow Arts Notation Guide": "verified_level1_guide_page_seo_48",
  "Type 1 LOOPs in The Kinetic Alphabet flow arts notation.": "verified_level1_guide_page_seo_49",
  "The γ→γ letters can connect to any other γ→γ letter.": "verified_level1_guide_page_seo_50",
  "Gamma LOOPs · Flow Arts Notation Guide": "verified_level1_guide_page_seo_51",
  "Type 2 LOOPs · Flow Arts Notation Guide": "verified_level1_guide_page_seo_52",
  "16-Count Sequences · Flow Arts Notation Guide": "verified_level1_guide_page_seo_53",
  "Words can be any length.": "verified_level1_guide_page_seo_54",
  "8-Letter Words · Flow Arts Notation Guide": "verified_level1_guide_page_seo_55",
  "Each of these words uses a prop-reversal.": "verified_level1_guide_page_seo_56",
  "Prop-Reversal LOOPs · Flow Arts Notation Guide": "verified_level1_guide_page_seo_57",
  "Each of these words uses a full-reversal.": "verified_level1_guide_page_seo_58",
  "Full-Reversal LOOPs · Flow Arts Notation Guide": "verified_level1_guide_page_seo_59",
  "The Codex · Flow Arts Notation Guide": "verified_level1_guide_page_seo_60",
  "The Codex in The Kinetic Alphabet flow arts notation.": "verified_level1_guide_page_seo_61",
  "The Codex, Continued · Flow Arts Notation Guide": "verified_level1_guide_page_seo_62",
  "The Codex, Continued in The Kinetic Alphabet flow arts notation.": "verified_level1_guide_page_seo_63",
  "Magic Potion": "verified_level1_print_magic_potion",
  "Never Quit": "verified_level1_print_never_quit",
  "Open Road": "verified_level1_print_open_road",
  "Disco Jam": "verified_level1_print_disco_jam",
  "Exploding Kitten": "verified_level1_print_exploding_kitten",
  "Fruity Loops": "verified_level1_print_fruity_loops",
  "Rotated LOOP": "verified_level1_print_rotated_loop",
  "Mirrored + Swapped LOOP": "verified_level1_print_mirrored_swapped_loop",
  "OPEN": "verified_level1_print_open",
  "CLOSE": "verified_level1_print_close",
} as const;

export function localizeLevel1Text(value: string): string {
  const key = keyByText[value as keyof typeof keyByText];
  return key ? t(key) : value;
}

export function localizeLevel1SelectionLabel(label: string): string {
  const replacements: Array<[RegExp, string]> = [
    [/^Animate AABB starting thumbs (.+)$/, "verified_level1_animate_aabb"],
    [/^Animate letter (.+) \((.+)\)$/, "verified_level1_animate_letter_mode"],
    [/^Animate letter (.+)$/, "verified_level1_animate_letter"],
    [/^Animate the word (.+)$/, "verified_level1_animate_word"],
    [/^Animate the (.+) LOOP$/, "verified_level1_animate_loop"],
    [/^Animate the (.+) sequence$/, "verified_level1_animate_sequence"],
    [/^Animate the (.+) combination$/, "verified_level1_animate_combination"],
    [/^Animate the (.+) (left|right) reversal$/, "verified_level1_animate_reversal"],
    [/^Animate (.+)$/, "verified_level1_animate_generic"],
  ];
  for (const [pattern, key] of replacements) {
    const match = pattern.exec(label);
    if (match) {
      const name = localizeLevel1Text(match[1]!);
      const mode = localizeLevel1Text(match[2] ?? "");
      switch (key) {
        case "verified_level1_animate_aabb": return t(key, { name });
        case "verified_level1_animate_letter_mode": return t(key, { name, mode });
        case "verified_level1_animate_letter": return t(key, { name });
        case "verified_level1_animate_word": return t(key, { name });
        case "verified_level1_animate_loop": return t(key, { name });
        case "verified_level1_animate_sequence": return t(key, { name });
        case "verified_level1_animate_combination": return t(key, { name });
        case "verified_level1_animate_reversal": return t(key, { name, mode });
        default: return t("verified_level1_animate_generic", { name });
      }
    }
  }
  return label;
}

export function localizeLevel1Block(block: GuideBlock): GuideBlock {
  switch (block.kind) {
    case "heading":
      return { ...block, text: localizeLevel1Text(block.text) };
    case "prose":
      return { ...block, html: localizeLevel1Text(block.html) };
    case "glyphImage":
      return { ...block, alt: localizeLevel1Text(block.alt) };
    case "pictograph":
    case "gridFigure":
      return { ...block, caption: block.caption ? localizeLevel1Text(block.caption) : undefined };
    case "pictographGroup":
      return {
        ...block,
        caption: block.caption ? localizeLevel1Text(block.caption) : undefined,
        stepLabels: block.stepLabels?.map(localizeLevel1Text),
        pool: block.pool && {
          ...block.pool,
          entries: block.pool.entries.map((entry) => ({
            ...entry,
            loopLabel: localizeLevel1Text(entry.loopLabel),
            proseHtml: localizeLevel1Text(entry.proseHtml),
          })),
        },
      };
    case "gridExplorer":
      return {
        ...block,
        modes: block.modes.map((mode) => ({
          ...mode,
          label: localizeLevel1Text(mode.label),
          ariaLabel: localizeLevel1Text(mode.ariaLabel),
        })),
      };
    case "printOnly":
      return {
        ...block,
        sheetHtml: localizeLevel1Text(block.sheetHtml),
        flow: block.flow.map(localizeLevel1Block),
      };
    default:
      return block;
  }
}
