// Generated by scripts/generate-color-presets.mjs. Do not edit by hand.
// 12 hues x 4 rows (light, vivid, deep, neutral) chosen in OKLCH. The light
// and deep rows share one perceived lightness; the vivid row sits at each
// hue's gamut cusp (its most saturated sRGB color). 48 divides by 12, 8 and
// 6, so the swatch grid never ends on a short row.
export type ColorPresetRow = "light" | "vivid" | "deep" | "neutral";

export interface ColorPreset {
  readonly hex: string;
  readonly name: string;
  readonly row: ColorPresetRow;
}

export const COLOR_PRESET_COLUMNS = 12;

export const COLOR_PRESETS: readonly ColorPreset[] = [
  { hex: "#ffaba3", name: "Light red", row: "light" },
  { hex: "#fcb17e", name: "Light orange", row: "light" },
  { hex: "#e5bf6d", name: "Light gold", row: "light" },
  { hex: "#c2cd77", name: "Light yellow", row: "light" },
  { hex: "#96d798", name: "Light green", row: "light" },
  { hex: "#6ddcc0", name: "Light teal", row: "light" },
  { hex: "#5ed9e6", name: "Light cyan", row: "light" },
  { hex: "#7dcffe", name: "Light sky", row: "light" },
  { hex: "#a8c4fe", name: "Light blue", row: "light" },
  { hex: "#c8b7ff", name: "Light violet", row: "light" },
  { hex: "#e9abec", name: "Light magenta", row: "light" },
  { hex: "#fda6c8", name: "Light pink", row: "light" },
  { hex: "#fe052c", name: "Red", row: "vivid" },
  { hex: "#ff8506", name: "Orange", row: "vivid" },
  { hex: "#fdc001", name: "Gold", row: "vivid" },
  { hex: "#eafc01", name: "Yellow", row: "vivid" },
  { hex: "#00fd49", name: "Green", row: "vivid" },
  { hex: "#0bfcd3", name: "Teal", row: "vivid" },
  { hex: "#00eafd", name: "Cyan", row: "vivid" },
  { hex: "#07b8fe", name: "Sky", row: "vivid" },
  { hex: "#0e05fe", name: "Blue", row: "vivid" },
  { hex: "#8305ff", name: "Violet", row: "vivid" },
  { hex: "#f007ff", name: "Magenta", row: "vivid" },
  { hex: "#fd0397", name: "Pink", row: "vivid" },
  { hex: "#a5292b", name: "Deep red", row: "deep" },
  { hex: "#8f4802", name: "Deep orange", row: "deep" },
  { hex: "#775801", name: "Deep gold", row: "deep" },
  { hex: "#5c6402", name: "Deep yellow", row: "deep" },
  { hex: "#02721c", name: "Deep green", row: "deep" },
  { hex: "#026e5b", name: "Deep teal", row: "deep" },
  { hex: "#086a73", name: "Deep cyan", row: "deep" },
  { hex: "#06658e", name: "Deep sky", row: "deep" },
  { hex: "#3055b6", name: "Deep blue", row: "deep" },
  { hex: "#6744ac", name: "Deep violet", row: "deep" },
  { hex: "#88358e", name: "Deep magenta", row: "deep" },
  { hex: "#9d2962", name: "Deep pink", row: "deep" },
  { hex: "#ffffff", name: "White", row: "neutral" },
  { hex: "#e1e1e1", name: "Grey 91", row: "neutral" },
  { hex: "#c3c3c3", name: "Grey 82", row: "neutral" },
  { hex: "#a7a7a7", name: "Grey 73", row: "neutral" },
  { hex: "#8b8b8b", name: "Grey 64", row: "neutral" },
  { hex: "#707070", name: "Grey 55", row: "neutral" },
  { hex: "#565656", name: "Grey 45", row: "neutral" },
  { hex: "#3e3e3e", name: "Grey 36", row: "neutral" },
  { hex: "#272727", name: "Grey 27", row: "neutral" },
  { hex: "#121212", name: "Grey 18", row: "neutral" },
  { hex: "#020202", name: "Grey 9", row: "neutral" },
  { hex: "#000000", name: "Black", row: "neutral" },
];
