// Generated by scripts/generate-color-presets.mjs. Do not edit by hand.
// 12 hues x 4 rows (light, vivid, deep, neutral) chosen in OKLCH. The light
// and deep rows share one perceived lightness; the vivid row sits at each
// hue's gamut cusp (its most saturated sRGB color). 48 divides by 12, 8 and
// 6, so the swatch grid never ends on a short row.
import { t } from "#lib/shared/i18n/i18n.svelte.js";

export type ColorPresetRow = "light" | "vivid" | "deep" | "neutral";

export interface ColorPreset {
  readonly hex: string;
  readonly name: string;
  readonly row: ColorPresetRow;
}

export const COLOR_PRESET_COLUMNS = 12;

export const COLOR_PRESETS: readonly ColorPreset[] = [
  { hex: "#ffaba3", get name() { return t("color_preset_light_red"); }, row: "light" },
  { hex: "#fcb17e", get name() { return t("color_preset_light_orange"); }, row: "light" },
  { hex: "#e5bf6d", get name() { return t("color_preset_light_gold"); }, row: "light" },
  { hex: "#c2cd77", get name() { return t("color_preset_light_yellow"); }, row: "light" },
  { hex: "#96d798", get name() { return t("color_preset_light_green"); }, row: "light" },
  { hex: "#6ddcc0", get name() { return t("color_preset_light_teal"); }, row: "light" },
  { hex: "#5ed9e6", get name() { return t("color_preset_light_cyan"); }, row: "light" },
  { hex: "#7dcffe", get name() { return t("color_preset_light_sky"); }, row: "light" },
  { hex: "#a8c4fe", get name() { return t("color_preset_light_blue"); }, row: "light" },
  { hex: "#c8b7ff", get name() { return t("color_preset_light_violet"); }, row: "light" },
  { hex: "#e9abec", get name() { return t("color_preset_light_magenta"); }, row: "light" },
  { hex: "#fda6c8", get name() { return t("color_preset_light_pink"); }, row: "light" },
  { hex: "#fe052c", get name() { return t("color_preset_red"); }, row: "vivid" },
  { hex: "#ff8506", get name() { return t("color_preset_orange"); }, row: "vivid" },
  { hex: "#fdc001", get name() { return t("color_preset_gold"); }, row: "vivid" },
  { hex: "#eafc01", get name() { return t("color_preset_yellow"); }, row: "vivid" },
  { hex: "#00fd49", get name() { return t("color_preset_green"); }, row: "vivid" },
  { hex: "#0bfcd3", get name() { return t("color_preset_teal"); }, row: "vivid" },
  { hex: "#00eafd", get name() { return t("color_preset_cyan"); }, row: "vivid" },
  { hex: "#07b8fe", get name() { return t("color_preset_sky"); }, row: "vivid" },
  { hex: "#0e05fe", get name() { return t("color_preset_blue"); }, row: "vivid" },
  { hex: "#8305ff", get name() { return t("color_preset_violet"); }, row: "vivid" },
  { hex: "#f007ff", get name() { return t("color_preset_magenta"); }, row: "vivid" },
  { hex: "#fd0397", get name() { return t("color_preset_pink"); }, row: "vivid" },
  { hex: "#a5292b", get name() { return t("color_preset_deep_red"); }, row: "deep" },
  { hex: "#8f4802", get name() { return t("color_preset_deep_orange"); }, row: "deep" },
  { hex: "#775801", get name() { return t("color_preset_deep_gold"); }, row: "deep" },
  { hex: "#5c6402", get name() { return t("color_preset_deep_yellow"); }, row: "deep" },
  { hex: "#02721c", get name() { return t("color_preset_deep_green"); }, row: "deep" },
  { hex: "#026e5b", get name() { return t("color_preset_deep_teal"); }, row: "deep" },
  { hex: "#086a73", get name() { return t("color_preset_deep_cyan"); }, row: "deep" },
  { hex: "#06658e", get name() { return t("color_preset_deep_sky"); }, row: "deep" },
  { hex: "#3055b6", get name() { return t("color_preset_deep_blue"); }, row: "deep" },
  { hex: "#6744ac", get name() { return t("color_preset_deep_violet"); }, row: "deep" },
  { hex: "#88358e", get name() { return t("color_preset_deep_magenta"); }, row: "deep" },
  { hex: "#9d2962", get name() { return t("color_preset_deep_pink"); }, row: "deep" },
  { hex: "#ffffff", get name() { return t("color_preset_white"); }, row: "neutral" },
  { hex: "#e1e1e1", get name() { return t("color_preset_grey_91"); }, row: "neutral" },
  { hex: "#c3c3c3", get name() { return t("color_preset_grey_82"); }, row: "neutral" },
  { hex: "#a7a7a7", get name() { return t("color_preset_grey_73"); }, row: "neutral" },
  { hex: "#8b8b8b", get name() { return t("color_preset_grey_64"); }, row: "neutral" },
  { hex: "#707070", get name() { return t("color_preset_grey_55"); }, row: "neutral" },
  { hex: "#565656", get name() { return t("color_preset_grey_45"); }, row: "neutral" },
  { hex: "#3e3e3e", get name() { return t("color_preset_grey_36"); }, row: "neutral" },
  { hex: "#272727", get name() { return t("color_preset_grey_27"); }, row: "neutral" },
  { hex: "#121212", get name() { return t("color_preset_grey_18"); }, row: "neutral" },
  { hex: "#020202", get name() { return t("color_preset_grey_9"); }, row: "neutral" },
  { hex: "#000000", get name() { return t("color_preset_black"); }, row: "neutral" },
];
