import { t } from "#lib/shared/i18n/i18n.svelte.js";
import type { TranslationKey } from "#lib/shared/i18n/i18n-types.js";

const KEYS: Readonly<Record<string, TranslationKey>> = {
  trigger: "effect_deep_trait_trigger",
  reach: "effect_deep_trait_reach",
  movement: "effect_deep_trait_movement",
  flutter: "effect_deep_trait_flutter",
  crystals: "effect_deep_trait_crystals",
  splatter: "effect_deep_trait_splatter",
  curl: "effect_deep_trait_curl",
  carry: "effect_deep_trait_carry",
  rise: "effect_deep_trait_rise",
  motion: "effect_deep_trait_motion",
  glow: "effect_deep_trait_glow",
  persistence: "effect_deep_trait_persistence",
  hang: "effect_deep_trait_hang",
  "strikes/s": "effect_deep_trait_strikes_s",
  spread: "effect_deep_trait_spread",
  intensity: "effect_deep_trait_intensity",
  path: "effect_deep_trait_path",
  "Ready to apply": "effect_deep_trait_ready_to_apply",
  "Dual color": "effect_deep_trait_dual_color",
  Spectrum: "effect_deep_trait_spectrum",
  Afterimage: "effect_deep_trait_afterimage",
  "Ember field": "effect_deep_trait_ember_field",
  "Live flame": "effect_deep_trait_live_flame",
  Chase: "effect_deep_name_chase",
  "Prop Colors": "effect_deep_name_prop_colors",
  Gradient: "effect_deep_name_gradient",
  "Staff 200": "effect_deep_name_staff_200",
  "Staff 72": "effect_deep_name_staff_72",
  "Staff 32": "effect_deep_name_staff_32",
  Zap: "effect_deep_name_zap",
  Wisp: "effect_deep_name_wisp",
  "Wide far-thrown fan": "effect_deep_name_wide_far_thrown_fan",
  "Wide fading coal glow": "effect_deep_name_wide_fading_coal_glow",
  Whisper: "effect_deep_name_whisper",
  Whip: "effect_deep_name_whip",
  "Violet sparks, soft drift": "effect_deep_name_violet_sparks_soft_drift",
  "Violet ghost flame": "effect_deep_name_violet_ghost_flame",
  "Violet Ember": "effect_deep_name_violet_ember",
  Trails: "effect_deep_name_trails",
  Toxic: "effect_deep_name_toxic",
  Tornado: "effect_deep_name_tornado",
  "Tight burst of hot sparks": "effect_deep_name_tight_burst_of_hot_sparks",
  "Thin electric ribbons": "effect_deep_name_thin_electric_ribbons",
  Tesla: "effect_deep_name_tesla",
  Supernova: "effect_deep_name_supernova",
  Streamer: "effect_deep_name_streamer",
  "Steel Wool": "effect_deep_name_steel_wool",
  Starfall: "effect_deep_name_starfall",
  "Spirit Veil": "effect_deep_name_spirit_veil",
  "Sparse green motes": "effect_deep_name_sparse_green_motes",
  Sparkle: "effect_deep_name_sparkle",
  "Soft photographic glow": "effect_deep_name_soft_photographic_glow",
  Smoke: "effect_deep_name_smoke",
  Silk: "effect_deep_name_silk",
  Shockwave: "effect_deep_name_shockwave",
  "Sharp diffraction flare": "effect_deep_name_sharp_diffraction_flare",
  Serpent: "effect_deep_name_serpent",
  Royal: "effect_deep_name_royal",
  "Rainbow POV": "effect_deep_name_rainbow_pov",
  Prism: "effect_deep_name_prism",
  Phantom: "effect_deep_name_phantom",
  Petals: "effect_deep_name_petals",
  "One point, drawn long": "effect_deep_name_one_point_drawn_long",
  "Neon Tag": "effect_deep_name_neon_tag",
  "Natural orange burn": "effect_deep_name_natural_orange_burn",
  "Long-exposure motion": "effect_deep_name_long_exposure_motion",
  "Liquid Fire": "effect_deep_name_liquid_fire",
  LED: "effect_deep_name_led",
  "Jungle Drift": "effect_deep_name_jungle_drift",
  "Jade Dust": "effect_deep_name_jade_dust",
  Iridescent: "effect_deep_name_iridescent",
  Ink: "effect_deep_name_ink",
  Inferno: "effect_deep_name_inferno",
  Inchworm: "effect_deep_name_inchworm",
  "Hot Coal": "effect_deep_name_hot_coal",
  Heartbeat: "effect_deep_name_heartbeat",
  Halo: "effect_deep_name_halo",
  Goo: "effect_deep_name_goo",
  Glitter: "effect_deep_name_glitter",
  "Gilt Wyrm": "effect_deep_name_gilt_wyrm",
  Gilded: "effect_deep_name_gilded",
  Ghost: "effect_deep_name_ghost",
  "Genie Burst": "effect_deep_name_genie_burst",
  "Full-spectrum light disc": "effect_deep_name_full_spectrum_light_disc",
  Fountain: "effect_deep_name_fountain",
  "Forge Burst": "effect_deep_name_forge_burst",
  "Fog Wall": "effect_deep_name_fog_wall",
  "Flowing molten body": "effect_deep_name_flowing_molten_body",
  "Flash Freeze": "effect_deep_name_flash_freeze",
  Fizz: "effect_deep_name_fizz",
  Fire: "effect_deep_name_fire",
  "Few fat embers, long hang": "effect_deep_name_few_fat_embers_long_hang",
  "Few embers, short fall": "effect_deep_name_few_embers_short_fall",
  "Fairy Dust": "effect_deep_name_fairy_dust",
  "Faint grey drift": "effect_deep_name_faint_grey_drift",
  "Ember Trail": "effect_deep_name_ember_trail",
  "Ember Drake": "effect_deep_name_ember_drake",
  "Ember Ash": "effect_deep_name_ember_ash",
  Dream: "effect_deep_name_dream",
  "Dense white-hot shower": "effect_deep_name_dense_white_hot_shower",
  Confetti: "effect_deep_name_confetti",
  Comet: "effect_deep_name_comet",
  "Cold gas-blue burn": "effect_deep_name_cold_gas_blue_burn",
  Coal: "effect_deep_name_coal",
  "Cinder Fan": "effect_deep_name_cinder_fan",
  "Capsule Pulse": "effect_deep_name_capsule_pulse",
  "Capsule Classic": "effect_deep_name_capsule_classic",
  Campfire: "effect_deep_name_campfire",
  Bubbles: "effect_deep_name_bubbles",
  "Breathing green tips": "effect_deep_name_breathing_green_tips",
  "One color per hand": "effect_deep_name_blue_and_red_shaft_ends",
  "Blue Flame": "effect_deep_name_blue_flame",
  Bloom: "effect_deep_name_bloom",
  "Banked Ember": "effect_deep_name_banked_ember",
  Animal: "effect_deep_name_animal",
  "Acid Fizz": "effect_deep_name_acid_fizz",
  Acid: "effect_deep_option_acid",
  Afterglow: "effect_deep_option_afterglow",
  Ambient: "effect_deep_option_ambient",
  Amount: "effect_deep_option_amount",
  "Animal creature": "effect_deep_option_animal_creature",
  "Animal palette": "effect_deep_option_animal_palette",
  "Animal tracking mode": "effect_deep_option_animal_tracking_mode",
  Ash: "effect_deep_option_ash",
  Asymmetry: "effect_deep_option_asymmetry",
  Aurora: "effect_deep_option_aurora",
  Autumn: "effect_deep_option_autumn",
  Beat: "effect_deep_option_beat",
  "Beat Interval": "effect_deep_option_beat_interval",
  "Black Ice": "effect_deep_option_black_ice",
  Blood: "effect_deep_option_blood",
  "Bloom color mode": "effect_deep_option_bloom_color_mode",
  "Bloom falloff": "effect_deep_option_bloom_falloff",
  Blossom: "effect_deep_option_blossom",
  Both: "effect_deep_option_both",
  Branching: "effect_deep_option_branching",
  Breath: "effect_deep_option_breath",
  Brightness: "effect_deep_option_brightness",
  "Bubbles palette": "effect_deep_option_bubbles_palette",
  "Bubbles tracking mode": "effect_deep_option_bubbles_tracking_mode",
  Burst: "effect_deep_option_burst",
  Camera: "effect_deep_option_camera",
  Capsule: "effect_deep_option_capsule",
  Carry: "effect_deep_option_carry",
  Caterpillar: "effect_deep_option_caterpillar",
  Champagne: "effect_deep_option_champagne",
  Chromatic: "effect_deep_option_chromatic",
  Classic: "effect_deep_option_classic",
  Color: "effect_deep_option_color",
  Colors: "effect_deep_option_colors",
  Continuous: "effect_deep_option_continuous",
  Core: "effect_deep_option_core",
  Creature: "effect_deep_option_creature",
  Curl: "effect_deep_option_curl",
  Cursed: "effect_deep_option_cursed",
  Custom: "effect_deep_option_custom",
  Diamond: "effect_deep_option_diamond",
  Dragon: "effect_deep_option_dragon",
  Drift: "effect_deep_option_drift",
  Duration: "effect_deep_option_duration",
  "Effect state unavailable.": "effect_deep_option_effect_state_unavailable",
  Ember: "effect_deep_option_ember",
  Ethereal: "effect_deep_option_ethereal",
  Exposure: "effect_deep_option_exposure",
  Eye: "effect_deep_option_eye",
  Fall: "effect_deep_option_fall",
  Falloff: "effect_deep_option_falloff",
  "Fire smoke": "effect_deep_option_fire_smoke",
  Flash: "effect_deep_option_flash",
  Flutter: "effect_deep_option_flutter",
  Fog: "effect_deep_option_fog",
  Frequency: "effect_deep_option_frequency",
  "Frost palette": "effect_deep_option_frost_palette",
  "Frost tracking mode": "effect_deep_option_frost_tracking_mode",
  Genie: "effect_deep_option_genie",
  Glacial: "effect_deep_option_glacial",
  Glare: "effect_deep_option_glare",
  Glow: "effect_deep_option_glow",
  Gold: "effect_deep_option_gold",
  "Gold Leaf": "effect_deep_option_gold_leaf",
  "Goo palette": "effect_deep_option_goo_palette",
  "Goo tracking mode": "effect_deep_option_goo_tracking_mode",
  Gravity: "effect_deep_option_gravity",
  Harmonics: "effect_deep_option_harmonics",
  Incense: "effect_deep_option_incense",
  India: "effect_deep_option_india",
  "Ink palette": "effect_deep_option_ink_palette",
  "Ink tracking mode": "effect_deep_option_ink_tracking_mode",
  Intensity: "effect_deep_option_intensity",
  Jitter: "effect_deep_option_jitter",
  Jungle: "effect_deep_option_jungle",
  Left: "effect_deep_option_left",
  Length: "effect_deep_option_length",
  Lifetime: "effect_deep_option_lifetime",
  Look: "effect_deep_option_look",
  Loop: "effect_deep_option_loop",
  Mercury: "effect_deep_option_mercury",
  Mode: "effect_deep_option_mode",
  Motion: "effect_deep_option_motion",
  Neon: "effect_deep_option_neon",
  Oil: "effect_deep_option_oil",
  Palette: "effect_deep_option_palette",
  Pattern: "effect_deep_option_pattern",
  Persistence: "effect_deep_option_persistence",
  "Petals palette": "effect_deep_option_petals_palette",
  "Petals tracking mode": "effect_deep_option_petals_tracking_mode",
  "Pixel staff, 200 LEDs": "effect_deep_option_pixel_staff_200_leds",
  "Pixel staff, 32 LEDs": "effect_deep_option_pixel_staff_32_leds",
  "Pixel staff, 72 LEDs": "effect_deep_option_pixel_staff_72_leds",
  Plasma: "effect_deep_option_plasma",
  Prop: "effect_deep_option_prop",
  Pulse: "effect_deep_option_pulse",
  "Pulse color mode": "effect_deep_option_pulse_color_mode",
  "Pulse palette": "effect_deep_option_pulse_palette",
  "Pulse style": "effect_deep_option_pulse_style",
  "Pulse tracking mode": "effect_deep_option_pulse_tracking_mode",
  "Pulse trigger mode": "effect_deep_option_pulse_trigger_mode",
  Radius: "effect_deep_option_radius",
  Rainbow: "effect_deep_option_rainbow",
  Rate: "effect_deep_option_rate",
  Reach: "effect_deep_option_reach",
  Right: "effect_deep_option_right",
  Ripple: "effect_deep_option_ripple",
  Rise: "effect_deep_option_rise",
  Ritual: "effect_deep_option_ritual",
  Satin: "effect_deep_option_satin",
  Shadow: "effect_deep_option_shadow",
  Sharp: "effect_deep_option_sharp",
  Shutter: "effect_deep_option_shutter",
  "Silk palette": "effect_deep_option_silk_palette",
  "Silk tracking mode": "effect_deep_option_silk_tracking_mode",
  Size: "effect_deep_option_size",
  Slither: "effect_deep_option_slither",
  "Smoke palette": "effect_deep_option_smoke_palette",
  "Smoke tracking mode": "effect_deep_option_smoke_tracking_mode",
  Smooth: "effect_deep_option_smooth",
  Snake: "effect_deep_option_snake",
  "Snowflake Size": "effect_deep_option_snowflake_size",
  Soap: "effect_deep_option_soap",
  Solid: "effect_deep_option_solid",
  Sonar: "effect_deep_option_sonar",
  "Sparkle color mode": "effect_deep_option_sparkle_color_mode",
  "Sparkle mode": "effect_deep_option_sparkle_mode",
  Spikes: "effect_deep_option_spikes",
  Spirit: "effect_deep_option_spirit",
  Splatter: "effect_deep_option_splatter",
  Spread: "effect_deep_option_spread",
  Storm: "effect_deep_option_storm",
  Streak: "effect_deep_option_streak",
  Stream: "effect_deep_option_stream",
  Stroke: "effect_deep_option_stroke",
  Style: "effect_deep_option_style",
  Sumi: "effect_deep_option_sumi",
  Tautness: "effect_deep_option_tautness",
  Thickness: "effect_deep_option_thickness",
  Tint: "effect_deep_option_tint",
  Tracking: "effect_deep_option_tracking",
  Trail: "effect_deep_option_trail",
  "Trail Length": "effect_deep_option_trail_length",
  Trigger: "effect_deep_option_trigger",
  "Vel. Threshold": "effect_deep_option_vel_threshold",
  Velocity: "effect_deep_option_velocity",
  "Velocity → Size": "effect_deep_option_velocity_size",
  Velvet: "effect_deep_option_velvet",
  Viscosity: "effect_deep_option_viscosity",
  Void: "effect_deep_option_void",
  Watercolor: "effect_deep_option_watercolor",
  Web: "effect_deep_option_web",
  Width: "effect_deep_option_width",
  "Wobble Amount": "effect_deep_option_wobble_amount",
  "Wobble Rate": "effect_deep_option_wobble_rate",
  "Zap style": "effect_deep_option_zap_style",
};

/** Localize display copy while preserving effect option values and presets. */
export function effectUiLabel(label: string): string {
  const key = KEYS[label];
  return key ? t(key) : label;
}

/** Localize generated preview traits without changing the preview model. */
export function effectUiTrait(trait: string): string {
  const [head, detail] = trait.split(" · ");
  // `split` on a non-empty separator always yields a defined first element;
  // this guard only satisfies noUncheckedIndexedAccess, it never actually
  // triggers when `detail` is present.
  if (head === undefined || !detail) return effectUiLabel(trait);
  const localizedHead = head.endsWith(" trigger")
    ? `${effectUiLabel(head.slice(0, -8))} ${effectUiLabel("trigger")}`
    : effectUiLabel(head);
  const match = detail.match(
    /^(.*) (path|intensity|spread|strikes\/s|hang|persistence|glow|motion|rise|carry|curl|splatter|crystals|flutter|movement|reach)$/
  );
  const unit = match?.[2];
  return `${localizedHead} · ${
    match && unit !== undefined ? `${match[1]} ${effectUiLabel(unit)}` : effectUiLabel(detail)
  }`;
}
