<script lang="ts">
  import { Canvas, T } from "@threlte/core";
  import { onMount } from "svelte";
  import OrbitControls from "$lib/shared/3d/components/OrbitControls.svelte";
  import { DEFAULT_LAB_CHARACTER_ID } from "../_lab-kit/lab-characters";
  import TransportControls from "$lib/shared/animation-engine/components/controls/TransportControls.svelte";
  import FilterChipBase from "$lib/shared/browse/components/filter-chips/FilterChipBase.svelte";
  import ReachStage from "./ReachStage.svelte";
  import { captureIsolationSnapshot, DEFAULT_TORSO_POSE_KEYFRAMES, ISOLATION_SEQUENCE, ISOLATION_STEP_COUNT, restoreIsolationSnapshot, torsoYawAtKeyframes, upsertTorsoKeyframe, wrapIsolationPhase, type IsolationSnapshot, type TorsoKeyframe } from "./isolation-loop";
  let playing = $state(true); let phase = $state(0); let torsoKeyframes = $state<TorsoKeyframe[]>(DEFAULT_TORSO_POSE_KEYFRAMES.map((keyframe) => ({ ...keyframe }))); let snapshots = $state<IsolationSnapshot[]>([]); let stage: HTMLElement | undefined; let reducedMotion = $state(false);
  const torsoYaw = $derived(torsoYawAtKeyframes(phase, torsoKeyframes));
  function seek(next: number) { playing = false; phase = wrapIsolationPhase(next); }
  function togglePlayback() { playing = !playing; }
  function editTorso(value: number) { torsoKeyframes = upsertTorsoKeyframe(torsoKeyframes, phase, value); }
  function saveSnapshot() { const canvas = stage?.querySelector("canvas"); if (canvas) snapshots = [...snapshots, captureIsolationSnapshot(canvas.toDataURL("image/png"), phase, torsoKeyframes)]; }
  function restoreSnapshot(snapshot: IsolationSnapshot) { const restored = restoreIsolationSnapshot(snapshot); phase = restored.phase; torsoKeyframes = restored.torsoKeyframes; playing = false; }
  onMount(() => { const media = matchMedia("(prefers-reduced-motion: reduce)"); const sync = () => reducedMotion = media.matches; sync(); media.addEventListener("change", sync); let last = performance.now(); let request = 0; const tick = (now: number) => { if (playing && !reducedMotion) phase = wrapIsolationPhase(phase + ((now - last) / 1000) * 0.32); last = now; request = requestAnimationFrame(tick); }; request = requestAnimationFrame(tick); return () => { cancelAnimationFrame(request); media.removeEventListener("change", sync); }; });
</script>
<svelte:head><title>Isolation loop · TKA lab</title></svelte:head>
<main class="lab"><section class="stage" bind:this={stage} aria-label="Single-hand staff isolation"><Canvas shadows rendererParameters={{ alpha: true, preserveDrawingBuffer: true }}><T.PerspectiveCamera makeDefault position={[0, 1.55, 3.8]} fov={34}><OrbitControls enableDamping enablePan={false} rightDragAction="rotate" target={[0, 1.25, 0]} minDistance={1.5} maxDistance={8} maxPolarAngle={Math.PI} /></T.PerspectiveCamera><ReachStage id="single-hand-isolation" {phase} active={false} {torsoYaw} sequence={ISOLATION_SEQUENCE} characterId={DEFAULT_LAB_CHARACTER_ID} /></Canvas></section><div class="controls" role="group" aria-label="Isolation controls"><TransportControls isPlaying={playing} onPlaybackToggle={togglePlayback} />{#each ["S", "E", "N", "W"] as marker, index}<FilterChipBase label={marker} mode="action" size="sm" onclick={() => seek(index)} />{/each}<label class="scrub"><span>Phase</span><input type="range" min="0" max={ISOLATION_STEP_COUNT} step="0.01" value={phase} oninput={(event) => seek(Number(event.currentTarget.value))} /></label><label class="scrub"><span>Turn</span><input type="range" min="-1.2" max="0.2" step="0.01" value={torsoYaw} oninput={(event) => editTorso(Number(event.currentTarget.value))} /></label><FilterChipBase label="Snapshot" icon="fa-solid fa-camera" mode="action" size="sm" onclick={saveSnapshot} />{#each snapshots as snapshot, index (snapshot.image)}<button class="snapshot" type="button" aria-label={`Restore snapshot ${index + 1}`} onclick={() => restoreSnapshot(snapshot)}><img src={snapshot.image} alt="" /></button>{/each}</div></main>
<style>.lab{height:100dvh;display:grid;grid-template-rows:minmax(0,1fr) auto;background:var(--theme-page-bg,#101217);color:var(--theme-text,#fff)}.stage{min-height:0}.stage :global(canvas){display:block;width:100%;height:100%}.controls{display:flex;align-items:center;gap:.75rem;flex-wrap:wrap;padding:.75rem clamp(.75rem,2vw,1.5rem);background:var(--theme-panel-bg,#1b1f27)}.scrub{display:grid;grid-template-columns:auto minmax(8rem,18rem);align-items:center;gap:.5rem;font-size:var(--font-size-compact,.75rem)}input[type=range]{accent-color:var(--theme-accent,#6e9cff);min-width:8rem}.snapshot{width:3rem;height:3rem;padding:0;border:1px solid var(--theme-stroke,#4c5566);background:transparent;cursor:pointer}.snapshot img{width:100%;height:100%;object-fit:cover;display:block}.snapshot:focus-visible,input:focus-visible{outline:2px solid var(--theme-accent,#6e9cff);outline-offset:2px}@media(max-width:42rem){.controls{align-content:start}.scrub{flex:1 1 100%;grid-template-columns:3rem 1fr}}</style>
